
#! /bin/bash

export SUBPACKAGE_DEEPJETCORE=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)
echo $SUBPACKAGE_DEEPJETCORE
export DEEPJETCORE_SUBPACKAGE=$SUBPACKAGE_DEEPJETCORE


cd $SUBPACKAGE_DEEPJETCORE
export PYTHONPATH=$SUBPACKAGE_DEEPJETCORE/modules:$PYTHONPATH
export PYTHONPATH=$SUBPACKAGE_DEEPJETCORE/modules/datastructures:$PYTHONPATH
export PATH=$SUBPACKAGE_DEEPJETCORE/scripts:$PATH

export LD_LIBRARY_PATH=$SUBPACKAGE_DEEPJETCORE/modules/compiled:$LD_LIBRARY_PATH
export PYTHONPATH=$SUBPACKAGE_DEEPJETCORE/modules/compiled:$PYTHONPATH

